services:
  - type: web
    name: pet-adoption-system
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false # Te pedirá rellenarla en el dashboard de Render
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
